import test from 'node:test'; import assert from 'node:assert/strict'; import { validators, ValidationError, validateWorkerResult, validateExecutionResult, validateAssuranceRecord, validateMemoryRecord, validateScopeContract, validateScopeDecision } from '../src/schemas/schemas.mjs';
import { normalizeScopeContract, scopeDigest } from '../src/policy/scope-engine.mjs';
test('all 21 mission record types have validators',()=>{ const expected=['WorkOrder','ProjectState','Session','SupervisorLease','ProviderWait','WorkerResult','ReviewVerdict','EvidenceRecord','MemoryRecord','ProvenanceRef','ConflictRef','ProcedureRecord','AssuranceRecord','EffectProposal','ApprovalRequest','ApprovalDecision','ExecutionResult','CapabilityRecord','RoutingDecision','ScopeContract','ScopeDecision']; for(const name of expected) assert.equal(typeof validators[name],'function',`validator missing: ${name}`); assert.equal(Object.keys(validators).length,expected.length); });
test('validators reject missing fields with named issues',()=>{ try{ validators.WorkOrder({id:'x'}); assert.fail('should throw'); }catch(e){ assert.ok(e instanceof ValidationError); assert.ok(e.issues.some((i)=>i.includes('objective'))); assert.ok(e.issues.some((i)=>i.includes('acceptance_criteria'))); }});
test('closed enums reject invented values',()=>{ assert.throws(()=>validateWorkerResult({session_id:'s',work_order_id:'w',actor:'a',role:'builder',outcome:'MOSTLY_PASSED',changed_files:[],checks:[],blockers:[],proposed_next_state:'READY_FOR_REVIEW',evidence_refs:[]}),ValidationError); assert.throws(()=>validateExecutionResult({id:'x',proposal_id:'p',proposal_digest:'a'.repeat(64),outcome:'PROBABLY_FINE',executed_at:new Date().toISOString(),retried_automatically:false}),ValidationError); });
test('execution results structurally forbid automatic retries',()=>{ assert.throws(()=>validateExecutionResult({id:'x',proposal_id:'p',proposal_digest:'a'.repeat(64),outcome:'FAIL',executed_at:new Date().toISOString(),retried_automatically:true}),ValidationError); });
test('assurance records require human creators at the schema level',()=>{ assert.throws(()=>validateAssuranceRecord({id:'x',kind:'approval',created_at:new Date().toISOString(),created_by:'model:gpt',created_by_role:'supervisor',payload:{}}),ValidationError); });
test('memory records require provenance and authority structures',()=>{ assert.throws(()=>validateMemoryRecord({id:'x',kind:'semantic',created_at:new Date().toISOString(),content:'c',confidence:'observed',schema_version:1,retention:'project',revoked:false,authority_revoked:false,lineage:{derived_from:[],conflicts_with:[]},authority:{class:'user-statement',admissible_uses:[]}}),ValidationError); });
test('scope schemas match restrictive runtime shapes',()=>{ const scope={project:'p',include_paths:['src/**'],exclude_paths:[],roles:['builder'],tools:['read'],memory_kinds:['semantic'],audiences:['project'],capabilities:['local-edit'],targets:['repository'],parameter_bounds:{files:{min:0,max:1}},budgets:{cost_usd:0,tokens:1,seconds:1,attempts:1},valid_from:'2026-08-21T00:00:00.000Z',valid_until:'2026-08-22T00:00:00.000Z',max_occurrences:1,externality:'internal',reversibility:'reversible',approval_required:false,data_classes:['project'],retention_classes:['session'],source_versions:['p@1']}; assert.equal(validateScopeContract(scope),scope); assert.equal(validateScopeDecision({verdict:'ALLOW',effective:scope,digest:scopeDigest(normalizeScopeContract(scope)),reasons:[],unresolved_dimensions:[]}).effective,scope); assert.throws(()=>validateScopeContract({...scope,budgets:{...scope.budgets,attempts:0}}),ValidationError); assert.throws(()=>validateScopeDecision({verdict:'GRANTED',effective:null,digest:'a'.repeat(64),reasons:[],unresolved_dimensions:[]}),ValidationError); });
