import test from 'node:test'; import assert from 'node:assert/strict'; import { acceptWorkerReturn, acceptReviewVerdict, reviewerPacket, RoleSeparationError } from '../src/workers/contracts.mjs'; const verdict=(over={})=>({id:'RV-1',work_order_id:'WO-1',reviewer:'reviewer:b',reviewer_role:'reviewer',builder:'builder:a',verdict:'PASS',diff_ref:'git:ref',evidence_refs:['ev-1'],findings:[],created_at:new Date().toISOString(),...over});
test('builder cannot approve/review own work (identity collision denied)',()=>{assert.throws(()=>acceptReviewVerdict(verdict({reviewer:'builder:a'}),{builderActor:'builder:a'}),RoleSeparationError);assert.throws(()=>acceptReviewVerdict(verdict({reviewer:'x',builder:'x'}),{builderActor:'x'}),RoleSeparationError);});
test('verdict must name the actual builder of the work order',()=>assert.throws(()=>acceptReviewVerdict(verdict({builder:'builder:someone-else'}),{builderActor:'builder:a'}),RoleSeparationError));
test('independent verdict from a distinct reviewer is accepted',()=>assert.equal(acceptReviewVerdict(verdict(),{builderActor:'builder:a'}).verdict,'PASS'));
test('review verdicts require the actual diff and evidence',()=>{assert.throws(()=>acceptReviewVerdict(verdict({diff_ref:undefined}),{builderActor:'builder:a'}));assert.throws(()=>acceptReviewVerdict(verdict({evidence_refs:[]}),{builderActor:'builder:a'}));});
test('reviewer packet requires diff and evidence (reviewer sees the change, not a summary)',()=>{const wo={id:'WO-1',objective:'o',acceptance_criteria:['c'],risk_class:'LOW'};assert.throws(()=>reviewerPacket({workOrder:wo,diffRef:null,evidence:[{id:'e'}],builderActor:'a'}),RoleSeparationError);assert.throws(()=>reviewerPacket({workOrder:wo,diffRef:'git:x',evidence:[],builderActor:'a'}),RoleSeparationError);const p=reviewerPacket({workOrder:wo,diffRef:'git:x',evidence:[{id:'e'}],builderActor:'a'});assert.ok(p.review_dimensions.some((d)=>d.includes('security')));});
test('reviewers cannot smuggle results through the builder return channel',()=>assert.throws(()=>acceptWorkerReturn({session_id:'s',work_order_id:'w',actor:'reviewer:b',role:'reviewer',outcome:'PASS',changed_files:[],checks:[],blockers:[],proposed_next_state:'DONE',evidence_refs:[]}),RoleSeparationError));

test('reviewer packet carries bounded security context without creating authority',()=>{const wo={id:'WO-1',objective:'o',acceptance_criteria:['c'],risk_class:'HIGH'};const securityContext={authorization_ref:'AUTH-17',scope_digest:'b'.repeat(64),clean_checkout_evidence:'ev-clean',bounds:{max_budget_usd:5,max_turns:20,max_seconds:900},expected_output_paths:['.state/evidence/strix/run-1/run.json','.state/evidence/strix/run-1/report.json']};const p=reviewerPacket({workOrder:wo,diffRef:'git:x',evidence:[{id:'e'}],builderActor:'a',securityContext});assert.deepEqual(p.security_context,securityContext);assert.equal('approved' in p.security_context,false);});

test('malformed reviewer security context is rejected',()=>{const wo={id:'WO-1',objective:'o',acceptance_criteria:['c'],risk_class:'HIGH'};const args={workOrder:wo,diffRef:'git:x',evidence:[{id:'e'}],builderActor:'a'};assert.throws(()=>reviewerPacket({...args,securityContext:{authorization_ref:'AUTH-17'}}),RoleSeparationError);assert.throws(()=>reviewerPacket({...args,securityContext:{authorization_ref:'AUTH-17',scope_digest:'b'.repeat(64),clean_checkout_evidence:'ev-clean',bounds:{max_budget_usd:5,max_turns:20,max_seconds:900},expected_output_paths:['../escape']}}),RoleSeparationError);});

test('reviewer security context rejects fields that could be mistaken for authority',()=>{const wo={id:'WO-1',objective:'o',acceptance_criteria:['c'],risk_class:'HIGH'};const securityContext={authorization_ref:'AUTH-17',scope_digest:'b'.repeat(64),clean_checkout_evidence:'ev-clean',bounds:{max_budget_usd:5,max_turns:20,max_seconds:900},expected_output_paths:['.state/evidence/strix/run-1/report.json'],approved:true};assert.throws(()=>reviewerPacket({workOrder:wo,diffRef:'git:x',evidence:[{id:'e'}],builderActor:'a',securityContext}),RoleSeparationError);});
